title:            Yocava
description:      油菜花科技
logo:             site-logo@2x.png
disqus_shortname: yocava
search:           true
#Change url to your domain. Leave localhost server or blank when working locally.
url:              http://www.yocava.com
baseurl:          /

# Owner/author information
owner:
  name:           油菜花科技
  company:        Yocava Ltd., Co.
  avatar:         avatar_clark.png
  email:          it@yocava.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        
  facebook:       
  github:         yocava
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  weibo:          yocava
  weixin:         yocava
  dajie:          yocava
  lagou:          yocava
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: 首页
    url: /
  - title: 产品
    url: /products
  - title: 博客
    url: /articles
  - title: 关于
    url: /about
  - title: 联系我们
    url: /contact
#  - title: Made Mistakes
#    url: http://mademistakes.com
#    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Chongqing
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title
relative_permalinks: false

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
